# Done to increase the memory available to gradle.
# Also add exports for google-java-format to work in modern java
org.gradle.jvmargs=-Xmx1G \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

org.gradle.caching=true
org.gradle.parallel=true

minecraft_version=26.1-snapshot-1

# Mod Properties
maven_group = dev.technici4n
archives_base_name = Modern-Dynamics
curseforge_project = 552758
modrinth_project = fMpvLrnF

# Dependencies
neoforge_version=26.1.0.0-alpha.3+snapshot-1

# In-dev runtime mods
rei_version=16.0.729

# latest jei versions: https://maven.blamejared.com/mezz/jei/jei-1.21.1-neoforge/maven-metadata.xml
jei_version=28.0.0.6
jei_minecraft_version=26.1-snapshot-1

emi_minecraft_version=1.21.1
emi_version=1.1.13

# Set to emi, jei, or rei to pick which tooltip mod gets picked at runtime
# for the dev environment.
runtime_itemlist_mod=jei

jade_file_id=7313008
