pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'net.neoforged.moddev' version '2.0.134'
        id 'com.matthewprenger.cursegradle' version '1.4.0'
        id 'com.modrinth.minotaur' version '2.+'
        id 'dev.lukebemish.immaculate' version '0.1.16'
    }
}

rootProject.name = "Modern-Dynamics"
