name: 'Release'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Generate assets
        run: ./gradlew runData --no-daemon
      - name: Build with Gradle
        env:
          MOD_VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew build
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/Modern-Dynamics-${{ github.event.release.tag_name }}.jar
          asset_name: moderndynamics-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/zip
      - name: Upload to Curseforge
        env:
          MOD_VERSION: ${{ github.event.release.tag_name }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: ./gradlew curseforge552758
      - name: Upload to Modrinth
        env:
          MOD_VERSION: ${{ github.event.release.tag_name }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
        run: ./gradlew publishModrinth
